name: Build and Create Installer

on:
  push:
    branches: [ main, contribution ]  # Triggers on push to main/dev
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # Required for Inno Setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Change to your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Release
      run: dotnet build --configuration Release --no-restore

    - name: Publish Application
      run: dotnet publish -c Release -o ./publish

    - name: Install Inno Setup
      run: choco install innosetup -y

    - name: Generate Installer
      run: |
        ISCC.exe /O"./publish" "./installer/ROBOT-RUNNER.iss"  # Update path to your .iss file
      shell: cmd

    - name: Upload Artifact (Installer)
      uses: actions/upload-artifact@v3
      with:
        name: ROBOT-RUNNER-Installer
        path: ./publish/*.exe  # Uploads the generated installer