name: Build and Create Installer

on:
  push:
    branches: [ main, dev ]  # Replace "dev" with your branch name
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # Use windows if you're building a .NET app

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Update to your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Create Installer
      run: |
        # Add your installer generation commands here.
        # Example for Inno Setup:
        ISCC.exe /O"./publish" "./PathToYourScript.iss"
      shell: cmd
